# Generated by Django 5.0.1 on 2024-03-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_imuser_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='permanent_login_fails',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='imuser',
            name='temporal_login_fails',
            field=models.IntegerField(default=0),
        ),
    ]
