# Generated by Django 5.0.1 on 2024-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_imuser_permanent_login_fails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
